#include "../cfgdefault/CFG_UART_Config_Default.h"
#include "../cfgdefault/CFG_BT_Default.h"
#include "../cfgdefault/CFG_SIM_CONFIG_Default.h"
#include "../cfgdefault/CFG_ADC_Default.h"
#include "../cfgdefault/CFG_BWCS_Default.h"
#include "../cfgdefault/CFG_Audio_Default.h"
#include "../cfgdefault/CFG_OMADMUSB_Default.h"
#include "../cfgdefault/CFG_MDTYPE_Default.h"
#include "../cfgdefault/CFG_EXT_MDTYPE_Default.h"
#include "../cfgdefault/CFG_SDIO_Default.h"
/* BUG1039 - Add NVRAM */
#include "../cfgdefault/CFG_CCI_SW_Default.h"
#include "../cfgdefault/CFG_CUST_COUNTRY_CODE_Default.h"
#include "../cfgdefault/CFG_CUST_EX_SW_Default.h"
#include "../cfgdefault/CFG_CUST_IN_SW_Default.h"
#include "../cfgdefault/CFG_CUST_PCB_SW_Default.h"
#include "../cfgdefault/CFG_FTM_TEST_RESULT_Default.h"
#include "../cfgdefault/CFG_HW_Default.h"
#include "../cfgdefault/CFG_P_SENSOR_THRESHOLD_Default.h"
#include "../cfgdefault/CFG_Warranty_Default.h"
#include "../cfgdefault/CFG_TWEAKER_Default.h"
#include "../cfgdefault/CFG_OPERATOR_Default.h"
/* BUG1039 - Add NVRAM */
