#include "../cfgfileinc/CFG_FACTORY_File.h"
#include "../cfgfileinc/CFG_BT_File.h"
#include "../cfgfileinc/CFG_BWCS_File.h"
#include "../cfgfileinc/CFG_Camera_File.h"
#include "../cfgfileinc/CFG_UART_File.h"
#include "../cfgfileinc/CFG_META_File.h"
#include "../cfgfileinc/CFG_SIM_File.h"
#include "../cfgfileinc/CFG_ADC_File.h"
#include "../cfgfileinc/CFG_HWMON_File.h"
#include "../cfgfileinc/CFG_UUID_File.h"
#include "../cfgfileinc/CFG_AUDIO_File.h"
#include "../cfgfileinc/CFG_OMADMUSB_File.h"
#include "../cfgfileinc/CFG_MDTYPE_File.h"
#include "../cfgfileinc/CFG_EXT_MDTYPE_File.h"
#include "../cfgfileinc/CFG_SDIO_File.h"
/* BUG1039 - Add NVRAM */
#include "../cfgfileinc/CFG_CCI_SW_File.h"
#include "../cfgfileinc/CFG_CUST_COUNTRY_CODE_File.h"
#include "../cfgfileinc/CFG_CUST_EX_SW_File.h"
#include "../cfgfileinc/CFG_CUST_IN_SW_File.h"
#include "../cfgfileinc/CFG_CUST_PCB_SW_File.h"
#include "../cfgfileinc/CFG_FTM_TEST_RESULT_File.h"
#include "../cfgfileinc/CFG_HW_File.h"
#include "../cfgfileinc/CFG_P_SENSOR_THRESHOLD_File.h"
#include "../cfgfileinc/CFG_Warranty_File.h"
#include "../cfgfileinc/CFG_TWEAKER_File.h"
#include "../cfgfileinc/CFG_OPERATOR_File.h"
/* BUG1039 - Add NVRAM */
